名称：名称：IPTV

  push：
分支机构：
      -        - 主要的
工作：
  建造：
    running-on :     运行：ubuntu-latest
    脚步：
      -名称:        - 名称：结帐代码
        使用：         使用：actions/checkout@v2
          -姓名
        使用：         使用：actions/setup-python@v2
        和：
          python-version :            python-版本：3.x
      - name :        - 名称：安装依赖项
        run :         运行：pip install selenium requests
      - name :        - 名称：安装 Chrome WebDriver
        运行：|
          LATEST_CHROMEDRIVER_VERSION=120.0.6099.109
          卷曲-sS -o chromedriver_linux64.zip“https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chrome-headless-shell-linux64.zip”
          sudo 解压 chromedriver_linux64.zip -d /usr/local/bin
          rm chromedriver_linux64.zip
      - name :        - name :设置 chromedriver 路径
        运行：|
          sudo ln -sf /usr/local/bin/chrome-headless-shell-linux64/chrome-headless-shell /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
      - name:       - 名称：运行脚本
        run:         运行： python ${{ github.workspace }}/IPTV.py{{ github.workspace }}/IPTV.py
      - name:       - 姓名：提交更改
        运行：|
          git config --local user.email“lxnew@126.com”
          git config --本地用户.name "jiandantv"
          git 添加 .
          git commit *.txt -m "添加生成的文件"
          git 推 -f
